### ISSUE TITLE
执行时报错，proxy库好像有问题

### ISSUE THREAD

**Issue by jayli517** [sunnywalden/scrapy_beauty#5]
已经更新升级新的proxy库了，但是执行的时候仍然显示：module 'proxy' has no attribute 'get_proxy'

**Comment by sunnywalden** [comment]
应该是包名冲突了，你可以通过find命令找找proxy目录或proxy.py文件。解决的话，可以通过pycharm等IDE的refactor功能直接将我的proxy.py重命名，比如get_proxy.py
